version: '3'

services:
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'

  redis:
    image: redis:5-alpine
    ports: ['6379']

  n8n:
    image: n8nio/n8n
    ports:
      - '5678:5678'
  imaginary:
    image: h2non/imaginary:latest
    volumes:
      - ./images:/mnt/data
    environment:
      PORT: 9000
    command: -enable-url-source -mount /mnt/data
    ports:
      - "9000:9000"

  rabbitmq:
    image: rabbitmq:3.7-management
    ports: ['5672', '15672']

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    ports:
      - 9090:9000
      - 9001:9001

volumes:
  db-data:
